---

#  https://redis.io/topics/admin Redis setup hint

- name: REDIS | Set Parameter's on sysctl
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: present
  with_items:
    - { name: 'vm.overcommit_memory', value: '1' }
    - { name: 'net.core.somaxconn', value: '65365'}
    - { name: 'net.ipv4.tcp_max_syn_backlog', value: '65535'}
    - { name: 'net.ipv4.ip_local_port_range', value: '1024 65535'}

- name: Edit rc.local to keep persistence on sysctl parameters
  lineinfile: 
    dest: /etc/rc.local
    regexp: "^{{ item.line }}"
    line: "{{ item.line }}"
  with_items: 
    - { line: sysctl -w net.core.somaxconn=65365 }
    - { line: sysctl -w vm.overcommit_memory=1 } 
    - { line: sysctl -w net.ipv4.tcp_max_syn_backlog=65535 } 
    - { line: sysctl -w net.ipv4.ip_local_port_range='1024 65535' } 
    - { line: echo never > /sys/kernel/mm/transparent_hugepage/enabled } 

- name: Source /etc/rc.local
  shell: source /etc/rc.local

- name: Increase Redis soft nofile limits
  pam_limits:
    domain: '{{ redis_user }}'
    limit_type: soft
    limit_item: nofile
    value: '{{ item.value }}'
  with_items:
    - { value: '65535' }

- name: Increase Redis hard nofile limit
  pam_limits:
    domain: '{{ redis_user }}'
    limit_type: hard
    limit_item: nofile
    value: '{{ item.value }}'
  with_items:
    - { value: '262144' }
