---
# vars file for kafka
kafka_user: "kafka"

kafka_download_dir: "/opt/"

kafka_url_src: "https://archive.apache.org/dist/kafka/0.9.0.1/kafka_2.10-0.9.0.1.tgz"
kafka_url_dest: "/opt/"

#kafka_service_src: "kafka.service.j2"
#kafka_prod_service_src: "kafkaprod.service.j2"
#kafka_service_dest: "/etc/systemd/system/kafka.service"
#kafka_service: "kafka"

file_transfer:
   - {
        src: kafka.yml,
        dest: /opt/jmx-exporter/kafka.yml,
        mode: 644,
        user: root,
        group: root,
     }
   - {
        src: jmx-exporter.jar,
        dest: /opt/jmx-exporter/jmx-exporter.jar,
        mode: 644,
        user: root,
        group: root,
     }
   - {
        src: kafka.service,
        dest: /etc/systemd/system/kafka.service,
        mode: 644,
        user: root,
        group: root,
     }
   - {
        src: kafka-server-start.sh,
        dest: /opt/kafka/bin/kafka-server-start.sh,
        mode: 644,
        user: root,
        group: root,
     }

kafka_dir:
   - { dir: /opt/kafka, mode: 755, user: kafka, group: kafka }
   - { dir: /vol/kafka, mode: 755, user: kafka, group: kafka }
   - { dir: /opt/jmx-exporter, mode: 755, user: root, group: root }
