---
- name: Download the SSM package
  get_url:
    dest: "{{ ssm_agent_dnl_dir }}"
    group: root
    owner: root
    mode: 0660
    url: "{{ ssm_agent_pkg_url }}/linux_amd64/{{ ssm_agent_pkg_name_deb }}"
  when: (ansible_facts.architecture == 'x86_64' and ansible_facts.distribution == 'Ubuntu' or ansible_facts.distribution == 'Debian' )



- name: Download the SSM package
  get_url:
    dest: "{{ ssm_agent_dnl_dir }}"
    group: root
    owner: root
    mode: 0660
    url: "{{ ssm_agent_pkg_url }}/linux_amd64/{{ ssm_agent_pkg_name_rpm }}"
  when: (ansible_facts.architecture == 'x86_64' and ansible_facts.distribution == 'Amazon' or ansible_facts.distribution == 'CentOS' )
