---
- name: Creating group kafka
  group:
    name: "{{ kafka_user }}"
    state: present

- name: Creating user kafka
  user:
    name: "{{ kafka_user }}"
    group: "{{ kafka_user }}"
    state: present
  become: true

- name: install xfs utilities
  yum:
    name: ["cloud-utils-growpart", "gdisk"]
    state: latest
  tags:
    - mount_vol

- name: "create mount path"
  file:
    state: "directory"
    path: "{{ item }}"
    mode: 0755
    owner: "{{ kafka_user }}"
    group: "{{ kafka_user }}"
  with_items:
    - "/vol"
    - "/vol/kafka"

- name: "mount the partition"
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "xfs"
    state: "mounted"
  with_items:
    - "{{ mount_path }}"
